### ISSUE TITLE
适用地区问题

### ISSUE THREAD

**Issue by JIeJaitt** [Reset12138/AutoFuckDaXueXi#1]
大佬，为啥暂时只适用甘肃地区啊，能有教程教我们怎么改嘛

**Comment by Reset816** [comment]
最近比较忙 还没时间做其他地区的 如果不咕咕咕的话挺想做的（

**Comment by Reset816** [comment]
每个省份大学习是单独统计的 单独的网址 虽然还没抓包看其他地方的 但我估计都差不多 只是改了网址

**Comment by JIeJaitt** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月12日(星期四) 下午2:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Reset12138/AutoFuckDaXueXi] 适用地区问题 (#1)

**Comment by JIeJaitt** [comment]
大佬，能教下我怎么抓包修改的嘛？我看仓库记得issue有人说抓包微信要开代理或者root，这些我都不会呀------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月12日(星期四) 下午2:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Reset12138/AutoFuckDaXueXi] 适用地区问题 (#1)

**Comment by Reset816** [comment]
> 大佬，能教下我怎么抓包修改的嘛？我看仓库记得issue有人说抓包微信要开代理或者root，这些我都不会呀------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年8月12日(星期四) 下午2:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Reset12138/AutoFuckDaXueXi] 适用地区问题 (#1)

Fiddler 之类的抓包软件，不需要开代理或者root，直接把链接发给电脑电脑打开就好了。想要在手机抓包的话开在wifi设置里面开代理。
你需要哪个省的？空了我可以优先适配一下

**Comment by JIeJaitt** [comment]
湖南省的，大佬能加个微信或者QQ交流一下嘛？邮件交流太麻烦了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月13日(星期五) 上午10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Reset12138/AutoFuckDaXueXi] 适用地区问题 (#1)

**Comment by Reset12138** [comment]
> 湖南省的，大佬能加个微信或者QQ交流一下嘛？邮件交流太麻烦了------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年8月13日(星期五) 上午10:10 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Reset12138/AutoFuckDaXueXi] 适用地区问题 (#1)

QQ 584266900

**Comment by Hebin-zhang** [comment]
你这码打了个寂寞（滑稽）

**Comment by Reset816** [comment]
> 你这码打了个寂寞（滑稽）

草好像确实

**Comment by yehuzhucha** [comment]
> > 大佬，能教下我怎么抓包修改的嘛？我看仓库记得issue有人说抓包微信要开代理或者root，这些我都不会呀------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年8月12日(星期四) 下午2:01 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [Reset12138/AutoFuckDaXueXi] 适用地区问题 (#1)
> 
> Fiddler 之类的抓包软件，不需要开代理或者root，直接把链接发给电脑电脑打开就好了。想要在手机抓包的话开在wifi设置里面开代理。 你需要哪个省的？空了我可以优先适配一下

大佬好，可以再留个联系方式吗，河北地区也想学习尝试一下，谢谢大佬！
